[package]
name = "vector_math_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Указывает компилятору собрать .wasm библиотеку

[dependencies]
# Using standard library collections and float math, no extra dependencies needed.

[profile.release]
opt-level = 3       # Максимальная оптимизация по скорости
lto = true          # Link-Time Optimization для удаления мертвого кода
codegen-units = 1   # Максимизирует возможности инлайнинга LLVM
panic = "abort"     # Убирает развесистый стек паники для микроскопического размера WASM
strip = true        # Вырезает все отладочные символы

